// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN1PxIxHsZ-ACIWnFKo7h2khkHgHH65zc',
    appId: '1:552497491306:web:9c5a74c1f6ec47e21bc913',
    messagingSenderId: '552497491306',
    projectId: 'financiaflutter',
    authDomain: 'financiaflutter.firebaseapp.com',
    storageBucket: 'financiaflutter.appspot.com',
    measurementId: 'G-BEGYS4R8DQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBThZXUYpPj5AHOd_4wiRxHELzdSkQDKrw',
    appId: '1:552497491306:android:f50f3d673a881ae61bc913',
    messagingSenderId: '552497491306',
    projectId: 'financiaflutter',
    storageBucket: 'financiaflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6prXctDrEPD7xrlDdofBHf8lsdhkGdPM',
    appId: '1:552497491306:ios:4f4d584e3a3478081bc913',
    messagingSenderId: '552497491306',
    projectId: 'financiaflutter',
    storageBucket: 'financiaflutter.appspot.com',
    iosClientId: '552497491306-74anuo8knopit2ptan31q07m3k9r3vq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.financiaMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6prXctDrEPD7xrlDdofBHf8lsdhkGdPM',
    appId: '1:552497491306:ios:4f4d584e3a3478081bc913',
    messagingSenderId: '552497491306',
    projectId: 'financiaflutter',
    storageBucket: 'financiaflutter.appspot.com',
    iosClientId: '552497491306-74anuo8knopit2ptan31q07m3k9r3vq3.apps.googleusercontent.com',
    iosBundleId: 'com.example.financiaMobileApp',
  );
}
